### ISSUE TITLE
Have consistency in errors related to lack of configuration

### ISSUE THREAD

**Issue by ahangarha** [shakacode/heroku-to-control-plane#104]
We should have consistent errors related to similar things. Look at the following:

```
➜  CPLN_ORG="   my-org  " cpl deploy-image 
No value provided for required options '--app'
➜  CPLN_APP=tutorial-app cpl deploy-image 
ERROR: Can't find option 'cpln_org' for app 'tutorial-app' in 'controlplane.yml', and CPLN_ORG env var is not set. The org can also be provided through --org.
```

Not just the messages but the colors are also different. The second message is in red, while the first one is in the terminal's default color.

**Comment by rafaelgomesxyz** [comment]
The reason for this is that the first error comes from Thor, so it might not be something we can easily customize (have to check the Thor docs), and the second error comes from our code.

**Comment by rafaelgomesxyz** [comment]
If we can't customize Thor's error message, we might be able to disable Thor's validation system and implement our own (we'd basically need to check if required args/options are present and match the defined types) - we might not want to spend too much time on this though.

**Comment by rafaelgomesxyz** [comment]
@ahangarha For this particular case (required arguments), see https://github.com/shakacode/heroku-to-control-plane/pull/109. I changed it so we handle them manually, so the errors are now consistent (for this case only).
