### ISSUE TITLE
Bug: `cpl delete` cannot delete the app with volumesets

### ISSUE THREAD

**Issue by ahangarha** [shakacode/heroku-to-control-plane#107]
If an app includes at least one volume set, `cpl delete` doesn't work.

Example:

```
cpl delete
Are you sure you want to delete 'tutorial-app'? (y/n) y

Deleting app 'tutorial-app'... failed!

ERROR: #<Net::HTTPBadRequest:0x00007f961881f5f0> {"message":"GVC tutorial-app cannot be deleted because it contains at least one volume set","status":400,"id":"XYZ"}
```

**Comment by justin808** [comment]
Legit issue. We NEED a confirmation prompt to retype the GVC name in case there is a volume set.

**Comment by rafaelgomesxyz** [comment]
I'm working on this.

@justin808 Do we need a second confirmation though? We already have:

![confirmation-1](https://github.com/shakacode/heroku-to-control-plane/assets/25509361/9f35795b-2356-400e-92c5-1138a5ab38f0)

What if we list the volumesets and images that will be deleted along with the app and then prompt for confirmation? Like this:

![confirmation-2](https://github.com/shakacode/heroku-to-control-plane/assets/25509361/a2aa2d4e-c4cd-4a2e-9154-910234d8fb46)
