### ISSUE TITLE
Support `-- cmd cmd-args` at the end  

### ISSUE THREAD

**Issue by justin808** [shakacode/heroku-to-control-plane#37]
Does Thor gem support parsing all text after `--` with no option as the command?

Or can we easily pull the remainder of the total command line after `-- `before parsing args with Thor?

We'd like to support the same structure for the command as:

https://docs.controlplane.com/reference/cli#workload-run

```
Command options:
  --               Command to execute on replica
``` 

So like this: 
```
cpln workload run --org demo-cpln-organization --gvc demo-gvc -- ls -al
```

**Comment by justin808** [comment]
https://github.com/shakacode/heroku-to-control-plane/blob/main/lib/command/run.rb#L45 should indicate that needs quotes if args passed like run:detached.

**Comment by justin808** [comment]
@rafaelgomesxyz 

```
      # Uses a different workload
      cpl run bash -a $APP_NAME -w other-workload
```

We need to update this doc to indicate that this means the `non-one-off-workload` from the controlplane.yml

```
    # Configure the workload name used as a template for one-off scripts, like a Heroku one-off dyno.
    one_off_workload: 
```

**Comment by rafaelgomesxyz** [comment]
That should already be possible. I've updated the docs in https://github.com/shakacode/heroku-to-control-plane/pull/39 to reflect it.
