### ISSUE TITLE
Add functionality to clean up database from review apps

### ISSUE THREAD

**Issue by justin808** [shakacode/heroku-to-control-plane#47]
overall we are still missing a "delete review databases" feature. Which can be something like "if db matches review app name exactly and there is no review app, delete such database"

However, I guess couple of things to consider:

- definitely it should not be enabled by default - only specifically
- it should somehow provide "main" database url (in our case staging) with permissions to show/drop databases
- it should not delete other databases, only exact match e.g. hichee-review-123 should be dropped but hichee-review-123-copy should not
- there is no db environment as this is a pure gem w/o rails, so no activerecord. as well we should not ask for psql tools. maybe we need to add some low-level "pg" gem that can do the trick. however, it may require native C pg libs. Dunno. But, anyway, we should try to make as minimal deps as possible.
- Alternative - this can be some rake db:clean_orpans task which is run from staging env (and have db connection and have active_record) which should be run with cpl run in app env.

🤷  whatever seems more easier to implement w/o adding heavy deps

**Comment by rafaelgomesxyz** [comment]
I think doing this in a Rake task on HiChee would be better, as we have access to the database there. In order to do it here, we would have to add dependencies that require psql tools, and I also don't think that database operations should be in the scope of this repo.
