### ISSUE TITLE
Improve orphan one-off workloads termination

### ISSUE THREAD

**Issue by dzirtusss** [shakacode/heroku-to-control-plane#51]
There is a possibility that user is disconnected fully (or gone into sleep) and `ensure` with workload destroy is not executed. After restoring connection, such one-off app continue running as orphan.

This is not a case with stale review-apps, as one-off may be running long as well for valid reasons.

I guess there might be a way to inject some code into run script that will self-destruct if connection to terminal session is lost. E.g. https://stackoverflow.com/questions/57003260/how-to-run-an-script-when-user-is-disconnected-from-ssh (but I haven't studied this in details), so maybe other methods can exist or be more robust.

*Alternatively* this may be solved in `cpln` *native* run command, which potentially we should upgrade our logic.

**Comment by justin808** [comment]
@rafaelgomesxyz still valid?

**Comment by rafaelgomesxyz** [comment]
No longer valid since we have the monitoring script for interactive mode now.
