### ISSUE TITLE
Grafana Docs

### ISSUE THREAD

**Issue by justin808** [shakacode/heroku-to-control-plane#52]
Where can I find detailed documentation and examples of setting up Grafana alerts for when container/replica/sidecar hits limits on memory and restarts?

I’d like to have my Heroku ==> CPLN docs refer to a master “cheat sheet” for an optimal setup and usage of Grafana. We should have some Loom walkthroughs as well.

**Comment by rafaelgomesxyz** [comment]
@justin808 We have the Grafana steps that I added with https://github.com/shakacode/heroku-to-control-plane/pull/50.
