### ISSUE TITLE
Add analogue of "wait" commands

### ISSUE THREAD

**Issue by dzirtusss** [shakacode/heroku-to-control-plane#54]
There is `ps:wait` commands on heroku which are rather useful. IMO, should not be hard to implement some analogue to wait for all replicas with old deployment to finish running (and destroyed).

This is useful for final "smoke-check" to be sure that requests are going only to newly deployed replicas and not accidentally served by old deprovisioning replicas.

**Comment by rafaelgomesxyz** [comment]
@dzirtusss We already have `ps:start --wait`, which waits until all workloads are ready, and `ps:stop --wait`, which waits until all workloads are not ready. Is that sufficient? Or do you think we still need to add a separate `ps:wait` command?

**Comment by dzirtusss** [comment]
@rafaelgomesxyz nop, basically process is:

1. trigger deployment (with whatever - image update, env update, restart, etc)
2. `ps:wait` - wait for **all** deployments to be ready

I mean there might be some similarities, but there is never explicit call of `ps:start` or `ps:stop`. However, dunno, maybe some functionality can be common - up to you.
