### ISSUE TITLE
Add support for template files containing multiple configs

### ISSUE THREAD

**Issue by ahangarha** [shakacode/heroku-to-control-plane#78]
Currently, if we want to apply a template containing multiple configs, separated by `---`, we only get the first configurations processed.

This is needed especially for more complex configurations such as [this](https://github.com/controlplane-com/examples/blob/main/examples/postgres/manifest.yaml).

**Comment by rafaelgomesxyz** [comment]
Good idea.

As a workaround, you can currently put each config in its own template and pass the template name to `cpl apply-template`.

**Comment by ahangarha** [comment]
@justin808 worked on this issue and should be able to make a PR in some time.

**Comment by justin808** [comment]
Fixed in #81.
