### ISSUE TITLE
Add support for getting app name from env variable

### ISSUE THREAD

**Issue by ahangarha** [shakacode/heroku-to-control-plane#79]
It would be handy to have a feature to set the app name from `APP_NAME` env variable if no app name is provided using `-a, --app` option.

This way, we can set the `APP_NAME` once and then run the commands without worrying about the app name.

**Comment by rafaelgomesxyz** [comment]
This is implemented by https://github.com/shakacode/heroku-to-control-plane/pull/88, with `CPLN_APP` env var.
