### ISSUE TITLE
Cannot run cpl --version out of a project with controlplane config

### ISSUE THREAD

**Issue by ahangarha** [shakacode/heroku-to-control-plane#93]
Using cpl `1.1.2`, I cannot run `cpl --version` unless I run the command inside a project with controlplane config file. This is the error:

```
ERROR: Can't find project config file at 'project_folder/.controlplane/controlplane.yml', please create it.
```

**Comment by justin808** [comment]
again, not important.

**Comment by ahangarha** [comment]
@justin808 
This is important to be fixed if we want to be able to add a generator. We should be able to run `cpl` in a location where we don't have ControlPlane configuration files.

I worked on it only when it was needed (when I started to implement the generator feature).
